-- STEP 2: Seed keywords table (Finance + AI)

-- Finance keywords
INSERT INTO keywords (keyword, category, subcategory, match_field) VALUES
  ('Accountant', 'Finance', 'Accounting', 'Both'),
  ('Chief Accountant', 'Finance', 'Accounting', 'Both'),
  ('Accounts Payable', 'Finance', 'Accounting', 'Both'),
  ('Accounts Receivable', 'Finance', 'Accounting', 'Both'),
  ('General Ledger', 'Finance', 'Accounting', 'Both'),
  ('GL Accountant', 'Finance', 'Accounting', 'Both'),
  ('Bookkeeper', 'Finance', 'Accounting', 'Both'),
  ('Month-end', 'Finance', 'Accounting', 'Both'),
  ('Year-end', 'Finance', 'Accounting', 'Both'),
  ('FP&A', 'Finance', 'FP&A', 'Both'),
  ('Financial Planning', 'Finance', 'FP&A', 'Both'),
  ('Financial Analysis', 'Finance', 'FP&A', 'Both'),
  ('Budgeting', 'Finance', 'FP&A', 'Both'),
  ('Forecasting', 'Finance', 'FP&A', 'Both'),
  ('Variance Analysis', 'Finance', 'FP&A', 'Both'),
  ('MIS', 'Finance', 'FP&A', 'Both'),
  ('Treasury', 'Finance', 'Treasury', 'Both'),
  ('Cash Management', 'Finance', 'Treasury', 'Both'),
  ('Liquidity', 'Finance', 'Treasury', 'Both'),
  ('Forex', 'Finance', 'Treasury', 'Both'),
  ('Hedging', 'Finance', 'Treasury', 'Both'),
  ('Treasury Analyst', 'Finance', 'Treasury', 'Both'),
  ('External Audit', 'Finance', 'External Audit', 'Both'),
  ('Statutory Audit', 'Finance', 'External Audit', 'Both'),
  ('Assurance', 'Finance', 'External Audit', 'Both'),
  ('Big 4', 'Finance', 'External Audit', 'Both'),
  ('Audit Senior', 'Finance', 'External Audit', 'Both'),
  ('Audit Manager', 'Finance', 'External Audit', 'Both'),
  ('Internal Audit', 'Finance', 'Internal Audit', 'Both'),
  ('Risk Based Audit', 'Finance', 'Internal Audit', 'Both'),
  ('CIA', 'Finance', 'Internal Audit', 'Both'),
  ('GRC', 'Finance', 'GRC', 'Both'),
  ('Governance', 'Finance', 'GRC', 'Both'),
  ('Compliance', 'Finance', 'GRC', 'Both'),
  ('SOX', 'Finance', 'GRC', 'Both'),
  ('Internal Controls', 'Finance', 'GRC', 'Both'),
  ('COSO', 'Finance', 'GRC', 'Both'),
  ('IFC', 'Finance', 'GRC', 'Both'),
  ('VAT', 'Finance', 'Tax', 'Both'),
  ('Zakat', 'Finance', 'Tax', 'Both'),
  ('Tax Compliance', 'Finance', 'Tax', 'Both'),
  ('Transfer Pricing', 'Finance', 'Tax', 'Both'),
  ('Tax Advisory', 'Finance', 'Tax', 'Both'),
  ('Financial Controller', 'Finance', 'Financial Control', 'Both'),
  ('Finance Manager', 'Finance', 'Financial Control', 'Both'),
  ('Finance Director', 'Finance', 'Financial Control', 'Both'),
  ('CFO', 'Finance', 'Financial Control', 'Both'),
  ('Chief Financial Officer', 'Finance', 'Financial Control', 'Both');

-- AI keywords
INSERT INTO keywords (keyword, category, subcategory, match_field) VALUES
  ('AI Engineer', 'AI', 'Engineering', 'Both'),
  ('ML Engineer', 'AI', 'Engineering', 'Both'),
  ('Machine Learning', 'AI', 'Engineering', 'Both'),
  ('Deep Learning', 'AI', 'Engineering', 'Both'),
  ('LLM', 'AI', 'Engineering', 'Both'),
  ('NLP', 'AI', 'Engineering', 'Both'),
  ('Data Scientist', 'AI', 'Data', 'Both'),
  ('Data Analyst', 'AI', 'Data', 'Both'),
  ('Data Engineer', 'AI', 'Data', 'Both'),
  ('Business Intelligence', 'AI', 'Data', 'Both'),
  ('Power BI', 'AI', 'Data', 'Both'),
  ('Tableau', 'AI', 'Data', 'Both'),
  ('AI Product Manager', 'AI', 'Product', 'Both'),
  ('AI Strategy', 'AI', 'Product', 'Both'),
  ('AI Consultant', 'AI', 'Product', 'Both'),
  ('MLOps', 'AI', 'Operations', 'Both'),
  ('AI Operations', 'AI', 'Operations', 'Both'),
  ('AI Implementation', 'AI', 'Operations', 'Both'),
  ('Artificial Intelligence', 'AI', 'General', 'Both'),
  ('Generative AI', 'AI', 'General', 'Both'),
  ('Prompt Engineer', 'AI', 'General', 'Both'),
  ('ChatGPT', 'AI', 'General', 'Both'),
  ('Copilot', 'AI', 'General', 'Both');
